template = "https://github.com/giellalt/template-lang-und"
rev_id = 271
template_sha = "58889500fa56906fc67098b753f74968988220af"

[replacements]
__GLOTTOLOG_ID__ = "kich1262"
__REPO__ = "lang-quc-x-ext-apertium"
__UND2C__ = "quc"
__UNDEFINED__ = "K'iche'"
__UND__ = "quc"
