template = "https://github.com/giellalt/template-lang-und"
rev_id = 278
template_sha = "58c9d1b66bc21da4ce588378206dd02d219954ae"

[replacements]
__GLOTTOLOG_ID__ = "kich1262"
__REPO__ = "lang-quc-x-ext-apertium"
__UND2C__ = "quc"
__UNDEFINED__ = "K'iche'"
__UND__ = "quc"
